server:
  port: 8080
  use-forward-headers: true
  tomcat:
    use-relative-redirects: true
toss:
  secret-key: test_sk_5OWRapdA8dvaJ2GK9zzBVo1zEqZK

spring:
  datasource:
    url: jdbc:h2:file:/opt/lms/lms-project/local;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: update
